include:
  - board: nice_nano_v2
    shield: skeletyl_left
  - board: nice_nano_v2
    shield: skeletyl_right
  - board: seeeduino_xiao_ble
    shield: skeletyl_dongle
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: testamatta_011
  - board: nice_nano_v2
    shield: waterfowl_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: waterfowl_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: ergodash_left
  - board: nice_nano_v2
    shield: ergodash_right