include:
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset

  - board: nice_nano_v2
    shield: skeletyl_left
  - board: nice_nano_v2
    shield: skeletyl_right
  - board: seeeduino_xiao_ble
    shield: skeletyl_dongle
  - board: nice_nano_v2
    shield: skeletyl_dongle_nice

  - board: seeeduino_xiao_ble
    shield: charybdis_dongle
  - board: nice_nano_v2
    shield: charybdis_dongle
  - board: nice_nano_v2
    shield: charybdis_left
  - board: nice_nano_v2
    shield: charybdis_right

  - board: seeeduino_xiao_ble
    shield: testamatta_011

  - board: nice_nano_v2
    shield: waterfowl_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: waterfowl_right nice_view_adapter nice_view

  - board: nice_nano_v2
    shield: ergodash_left
  - board: nice_nano_v2
    shield: ergodash_right

  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right

  - board: nice_nano_v2
    shield: klor_left
  - board: nice_nano_v2
    shield: klor_right