manifest:
  remotes:
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: jawick
      url-base: https://github.com/JW2586/zmk.git
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
    - name: ykz89
      url-base: https://github.com/ykz89
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware  
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-split-peripheral-input-relay
      remote: badjeff
      revision: main
    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main
    - name: zmk-fingerpunch-keyboards
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
    - name: chiptuner-zmk-module
      remote: petejohanson
      revision: main
  self:
    path: config
